
[[headers]]
  for = "/*"
  [headers.values]

    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
        default-src https://vemulakonda.com; 
        script-src 'self' 'unsafe-inline' 'unsafe-eval' *.cloudfront.net *.fontawesome.com *.netlify.com *.google-analytics.com https://www.googletagmanager.com https://unpkg.com https://vemulakonda.com; 
        connect-src 'self' *.staticman.net https://vemulakonda.com; 
        img-src 'self' *.cloudfront.net *.google-analytics.com https://vemulakonda.com; 
        style-src 'self' 'unsafe-inline' *.cloudfront.net https://vemulakonda.com;
        frame-ancestors https://vemulakonda.com; 
        frame-src https://vemulakonda.com;
      '''
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload; always;"
    
    # COMMENT: Multi-key header rules are expressed with multi-line strings
    Link = "</main.css>; rel=preload; as=stylesheet"

