
[[headers]]
  for = "/*"
  [headers.values]

    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    

    # COMMENT: Multi-key header rules are expressed with multi-line strings
    Link = '''
    </main.css>; rel=preload; as=stylesheet '''

